experiment_info:
  start_time: '2026-02-04 01:15:05'
  duration: 0:43:12
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 39
    - 158
    shape_X_path:
    - 112
    - 20
    - 107
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 3553
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Jump & Reach
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  aggregation: mean
  hidden_dim: 32
  depth: 1
  dropout: 0.2344689837775603
  lr: 0.0005261475848427091
  weight_decay: 6.475244889016832e-05
