experiment_info:
  start_time: '2026-01-30 15:23:02'
  duration: 0:16:22
  input_shapes:
    shape_X_ts:
    - 140
    - 20
    - 39
    - 158
    shape_X_path:
    - 140
    - 20
    - 107
    shape_X_user:
    - 140
    - 2
    shape_y:
    - 140
    - 4
  total_model_parameters: 11460
pipeline_config:
  epochs: 50
  hyperparameter_mode: default
  only_first_fold: false
  n_trials: 200
  use_lasso: false
  max_n_features: 20
  targets:
  - Balance Test
  - Single Leg Stance
  - Hand Grip Right
  - Throwing Beanbag at Target
  note: Third full hyperparmeter search with single targets
hyperparameters_fold_0:
  aggregation: mean
  hidden_dim: 64
  depth: 2
  dropout: 0.3
  lr: 0.001
  weight_decay: 0.0001
