experiment_info:
  start_time: '2026-02-28 19:43:06'
  duration: 0:51:07
  input_shapes:
    shape_X_ts:
    - 25
    - 20
    - 32
    - 15573
    shape_X_path:
    - 25
    - 20
    - 78
    shape_X_user:
    - 25
    - 2
    shape_y:
    - 25
    - 8
  total_model_parameters: 46749
  strategy: simple_tuning
  duration_final_test: 0:00:01
pipeline_config:
  epochs: 30
  hyperparameter_mode: optimize
  n_trials: 30
  early_stopping_patience: 2
  targets:
  - Robotrainer Front
  - Robotrainer Left
  - Robotrainer Right
  - Hand Grip Left
  - Hand Grip Right
  - Jump & Reach
  - Figure 8 Walk
  - Ruler Drop Test
  augmentation_ratio: 0
  note: First with early stopping
best_params:
  path_dim: 4
  dropout_path: 0.22655060308520866
  path_aggregation: flatten
  regressor_dim: 512
  dropout_reg: 0.30335589862608825
  lr: 0.0008887240577211731
  weight_decay: 0.002222430039021746
  batch_size: 6
  n_path_features: 30
