experiment_info:
  start_time: '2026-02-04 13:57:26'
  duration: 0:43:00
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 39
    - 158
    shape_X_path:
    - 112
    - 20
    - 105
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 108
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Jumping Sideways
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  aggregation: mean
  lr: 0.0008354213387408855
  alpha: 0.17738563436686933
  l1_ratio: 0.1846743521080045
