experiment_info:
  start_time: '2026-01-29 12:01:15'
  duration: '2:54:57'
  input_shapes:
    shape_X_ts:
    - 140
    - 20
    - 39
    - 158
    shape_X_path:
    - 140
    - 20
    - 107
    shape_X_user:
    - 140
    - 2
    shape_y:
    - 140
    - 4
  total_model_parameters: 7832
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 200
  use_lasso: false
  max_n_features: 20
  targets:
  - Balance Test
  - Single Leg Stance
  - Hand Grip Right
  - Throwing Beanbag at Target
  note: Third full hyperparmeter search with single targets
hyperparameters_fold_0:
  ts_out_channels: 16
  num_conv_layers: 2
  path_dim: 4
  regressor_dim: 256
  path_attention_type: mean
  lr: 0.00015565288829063982
  weight_decay: 0.0018028150752207402
  dropout: 0.3992962946066046
  batch_size: 16
