experiment_info:
  start_time: '2026-02-23 21:45:54'
  duration: 0:40:24
  input_shapes:
    shape_X_ts:
    - 25
    - 20
    - 32
    - 15573
    shape_X_path:
    - 25
    - 20
    - 78
    shape_X_user:
    - 25
    - 2
    shape_y:
    - 25
    - 8
  total_model_parameters: 0
  strategy: simple_tuning
  duration_final_test: 0:00:03
pipeline_config:
  epochs: 30
  hyperparameter_mode: optimize
  n_trials: 30
  targets:
  - Robotrainer Front
  - Robotrainer Left
  - Robotrainer Right
  - Hand Grip Left
  - Hand Grip Right
  - Jump & Reach
  - Figure 8 Walk
  - Ruler Drop Test
  augmentation_ratio: 0
  note: Single targets comparison
best_params:
  n_estimators: 500
  max_depth: 20
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: 0.5
  bootstrap: true
  n_path_features: 60
