experiment_info:
  start_time: '2026-02-04 16:11:13'
  duration: 0:49:41
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 39
    - 158
    shape_X_path:
    - 112
    - 20
    - 105
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 5601
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Jumping Sideways
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  aggregation: mean
  hidden_dim: 32
  depth: 3
  dropout: 0.2223503977904061
  lr: 0.0004885053270521747
  weight_decay: 0.0014960540847007507
