ARG USERIMAGE=project:tag
FROM ${USERIMAGE} AS user-stage

# Install custom dependencies
# RUN apt-get update && apt-get install --no-install-recommends -y \
#     <YOUR_PACKAGE> \
#     && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]