experiment_info:
  start_time: '2026-01-30 22:09:35'
  duration: 0:26:29
  input_shapes:
    shape_X_ts:
    - 84
    - 20
    - 39
    - 158
    shape_X_path:
    - 84
    - 20
    - 107
    shape_X_user:
    - 84
    - 2
    shape_y:
    - 84
    - 4
  total_model_parameters: 440
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Balance Test
  - Single Leg Stance
  - Hand Grip Right
  - Throwing Beanbag at Target
  augmentation_ratio: 2
  note: Full hyperparmeter search with augmentation ratio comparison
hyperparameters_fold_0:
  aggregation: mean
  lr: 0.0003127918932173388
  weight_decay: 1.989131429939446e-06
