experiment_info:
  start_time: '2026-02-23 21:25:10'
  duration: 0:20:41
  input_shapes:
    shape_X_ts:
    - 25
    - 20
    - 32
    - 15573
    shape_X_path:
    - 25
    - 20
    - 78
    shape_X_user:
    - 25
    - 2
    shape_y:
    - 25
    - 8
  total_model_parameters: 0
  strategy: simple_tuning
  duration_final_test: 0:00:01
pipeline_config:
  epochs: 30
  hyperparameter_mode: optimize
  n_trials: 30
  targets:
  - Robotrainer Front
  - Robotrainer Left
  - Robotrainer Right
  - Hand Grip Left
  - Hand Grip Right
  - Jump & Reach
  - Figure 8 Walk
  - Ruler Drop Test
  augmentation_ratio: 0
  note: Single targets comparison
best_params:
  kernel: linear
  C: 47.94113098310296
  epsilon: 0.2795553581365559
  shrinking: true
  n_path_features: 30
