experiment_info:
  start_time: '2026-02-04 17:02:02'
  duration: 0:59:18
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 39
    - 158
    shape_X_path:
    - 112
    - 20
    - 107
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 5269
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Throwing Beanbag at Target
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  ts_out_channels: 16
  num_conv_layers: 2
  path_dim: 4
  regressor_dim: 32
  path_attention_type: mean
  lr: 6.257738781164308e-05
  weight_decay: 0.003555450776742422
  dropout: 0.3006184062903595
  batch_size: 16
