experiment_info:
  start_time: '2026-02-04 06:54:01'
  duration: 0:56:12
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 38
    - 158
    shape_X_path:
    - 112
    - 20
    - 103
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 7497
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Figure 8 Walk
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  ts_out_channels: 16
  num_conv_layers: 2
  path_dim: 8
  regressor_dim: 128
  path_attention_type: mean
  lr: 0.0004183984589466405
  weight_decay: 0.002548886925095887
  dropout: 0.2429869318325877
  batch_size: 16
