experiment_info:
  start_time: '2026-02-05 04:35:48'
  duration: '1:10:38'
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 37
    - 158
    shape_X_path:
    - 112
    - 20
    - 102
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 24837
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Ruler Drop Test
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  lr: 0.0004911045834236071
  weight_decay: 0.0016455423628976543
  lstm_hidden_dim: 32
  lstm_layers: 2
  bidirectional: false
  dropout_lstm: 0.19177401137478017
  path_dim: 16
  dropout_path: 0.3245436867984527
  regressor_dim: 256
  dropout_reg: 0.25230801011613957
  path_aggregation: static
  batch_size: 16
