experiment_info:
  start_time: '2026-01-31 00:20:08'
  duration: 0:58:28
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 39
    - 158
    shape_X_path:
    - 112
    - 20
    - 107
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 4
  total_model_parameters: 6936
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Balance Test
  - Single Leg Stance
  - Hand Grip Right
  - Throwing Beanbag at Target
  augmentation_ratio: 3
  note: Full hyperparmeter search with augmentation ratio comparison
hyperparameters_fold_0:
  lr: 0.0001989265926950153
  weight_decay: 0.00019403671877171004
  lstm_hidden_dim: 8
  lstm_layers: 2
  bidirectional: false
  dropout_lstm: 0.2173987285841565
  path_dim: 8
  dropout_path: 0.24754918874626036
  regressor_dim: 256
  dropout_reg: 0.22640281371816007
  path_aggregation: static
  batch_size: 16
