import os
import numpy as np
import pandas as pd
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.pipeline import Pipeline
from collections import defaultdict
from scipy.stats import spearmanr
from typing import List, Tuple, Set, Dict

from automatic_assessment.framework.data.preprocessing import Preprocessor
from automatic_assessment.framework.data.dataset import DatasetConv1s

# ================= CONFIGURATION =================
IN_DIR = "/data/dataset_conv@1s"
OUT_DIR = "/data/dataset_conv@1s/pruned_random_forest"
TOP_K_SOURCES_PER_FOLD = 15    # Force model to pick only the "MVPs"
SELECTION_THRESHOLD = 0.5      # Standard for stability selection
N_ESTIMATORS = 500             # Stabilizes the importance scores
MAX_DEPTH = 4                  # Prevents memorizing single users
MIN_SAMPLES_LEAF = 3           # Requires at least 3 users to make a decision rule
MAX_FEATURES = "sqrt"          # Forces trees to look at diverse features
RANDOM_STATE = 42
MAX_TOP_N_TARGETS = 10         # Cap the maximum number of targets to analyze
SIMILARITY_THRESHOLD = 0.90    # Features with correlation > 0.95 are considered redundant
MAX_TOTAL_FEATURES = 50        # Global cap on total features to export
MAX_FEATURES_PER_SOURCE = 5    # Cap on features per source

os.makedirs(OUT_DIR, exist_ok=True)

# ================= HELPER: SOURCE MAPPING =================

# Suffixes generated by aab_data_augmentation.py
FEATURE_SUFFIXES = [
    "mean", "std", "p95", "p05", "skew", "kurtosis", 
    "sample_entropy", "autocorr_decay", "log_jerk", 
    "signal_energy", "rms", "power_voluntary", 
    "power_tremor", "tremor_ratio", "cv_abs_diff", 
    "rms_diff", "gini_amplitude", "peak_to_rms"
]

def get_source_name(feat_name: str, ts_source_set: Set[str]) -> str:
    """Maps 'force_x_mean' -> 'force_x' ONLY if 'force_x' is a known TS source."""
    for suffix in FEATURE_SUFFIXES:
        if feat_name.endswith(f"_{suffix}"):
            potential_source = feat_name.rsplit(f"_{suffix}", 1)[0]
            if potential_source in ts_source_set:
                return potential_source
    return feat_name

# ================= STEP 1: MERGE DATASETS =================

def merge_datasets(path: pd.DataFrame, user: pd.DataFrame) -> Tuple[pd.DataFrame, np.ndarray]:
    """
    Merges static Path (containing pre-calculated TS features) and User features.
    """
    print("Merging Datasets...")
    X_path = path.set_index(["user", "path"])
    X_user = user.set_index("user")
    X = X_path.join(X_user, on="user", how="left")
    
    # Handle NaNs
    X = X.fillna(0)
    
    # Reset index to separate columns for sklearn
    groups = X.index.get_level_values("user").to_numpy()
    return X, groups

# ================= STEP 2: TARGET LEARNABILITY CHECK =================

def filter_learnable_targets(X: pd.DataFrame, target_df: pd.DataFrame, groups: np.ndarray, min_keep: int = 5, max_keep: int = 10) -> List[str]:
    """
    Ranks targets by 'Scaled RMSE'. 
    Forces keeping at least 'min_keep' targets even if they perform poorly.
    Caps selection at 'max_keep' targets.
    
    Scaled RMSE = RMSE / Std_Dev_of_Target
    - < 1.0 : Model is better than Dummy (Mean)
    - = 1.0 : Model is equal to Dummy
    - > 1.0 : Model is worse (overfitting)
    """
    print("\n--- Analysing Target Learnability (Scaled RMSE) ---")
    
    logo = LeaveOneGroupOut()
    target_cols = [c for c in target_df.columns if c != "user"]
    
    # Align target DataFrame to X
    y_all = target_df.set_index("user").reindex(groups)

    # print shapes and number of features
    print(f"Users: {X.shape[0]} Features: {X.shape[1]} | Total Targets: {len(target_cols)}")
    
    results = []

    for t in target_cols:
        y = y_all[t]
        
        if y.isna().any():
            continue

        rmse_scaled_list = []
        dummy_scaled_list = []
        
        for train_idx, test_idx in logo.split(X, y, groups):
            X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
            y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

            # Calculate Training STD for scaling (avoid leakage from test set)
            y_train_std = y_train.std() + 1e-8
            
            # Simple Pipeline
            pipe = Pipeline([
                ('scaler', StandardScaler()),
                ('rf', RandomForestRegressor(
                    n_estimators=N_ESTIMATORS,   # 500
                    max_depth=MAX_DEPTH,         # 4
                    min_samples_leaf=MIN_SAMPLES_LEAF, # 3
                    max_features=MAX_FEATURES,   # "sqrt"
                    n_jobs=-1, 
                    random_state=RANDOM_STATE
                ))
            ])
            
            # Dummy Baseline
            dummy = DummyRegressor(strategy="mean")
            
            pipe.fit(X_train, y_train)
            dummy.fit(X_train, y_train)
            
            # Raw RMSE
            raw_rmse_model = np.sqrt(mean_squared_error(y_test, pipe.predict(X_test)))
            raw_rmse_dummy = np.sqrt(mean_squared_error(y_test, dummy.predict(X_test)))
            
            # Scaled RMSE (Normalized by this fold's training std)
            rmse_scaled_list.append(raw_rmse_model / y_train_std)
            dummy_scaled_list.append(raw_rmse_dummy / y_train_std)
            
        # Average across folds
        avg_srmse_model = np.mean(rmse_scaled_list)
        avg_srmse_dummy = np.mean(dummy_scaled_list) # Should be close to 1.0
        
        # Improvement vs Baseline (Positive is good)
        improvement = (avg_srmse_dummy - avg_srmse_model) / avg_srmse_dummy
        
        results.append({
            "target": t,
            "sRMSE": avg_srmse_model, 
            "Baseline_sRMSE": avg_srmse_dummy,
            "improvement %": improvement * 100
        })

    # Create DataFrame and Sort by sRMSE (lower is better)
    res_df = pd.DataFrame(results).sort_values("sRMSE", ascending=True)
    
    # Logic: Keep if sRMSE < 1.0 OR keep top K forced
    # We create a 'rank' column first
    res_df["rank"] = range(1, len(res_df) + 1)
    
    # condition: is learnable (< 1.0) OR is in top K
    # AND rank must be <= max_keep
    res_df["keep"] = ((res_df["sRMSE"] < 1.0) | (res_df["rank"] <= min_keep)) & (res_df["rank"] <= max_keep)
    
    print(res_df.round(4))
    
    selected_targets = res_df[res_df["keep"]]["target"].tolist()
    
    print(f"\nForcing Top {min_keep} Targets. Capping at {max_keep}. Keeping {len(selected_targets)} total.")
    
    return selected_targets

# ================= STEP 3: CORRELATION REPORTING =================

def analyze_correlations(X: pd.DataFrame, target_df: pd.DataFrame, groups: np.ndarray, valid_targets: List[str], ts_source_set: Set[str]) -> Dict[str, float]:
    """
    Calculates Spearman correlation of every feature against every valid target.
    Returns a dictionary mapping feature_name -> max_absolute_correlation.
    """
    print("\n--- Step 3: Correlation Analysis (Spearman) ---")
    
    # Pre-calculate correlations for all features vs all valid targets
    # Structure: source -> list of (feature_name, max_corr, best_target_name)
    source_stats = defaultdict(list)
    feature_max_corrs = {} # Store max correlation for each feature
    
    # Align target data once
    y_aligned = target_df.set_index("user").reindex(groups)

    for feat in X.columns:
        # Find best correlation for this feature across all valid targets
        best_r = 0
        best_t = ""
        
        feat_data = X[feat]
        # Check for constant input to avoid warnings
        if feat_data.std() < 1e-9:
            best_r = 0
            best_t = "None"
        else:
            for t in valid_targets:
                target_data = y_aligned[t]
                if target_data.std() < 1e-9:
                    continue
                    
                # Spearman is monotonic, good for non-linear relationships
                r, _ = spearmanr(feat_data, target_data)
                if abs(r) > abs(best_r):
                    best_r = r
                    best_t = t
        
        feature_max_corrs[feat] = abs(best_r)

        # Group by Source
        src = get_source_name(feat, ts_source_set)
        source_stats[src].append({
            "feature": feat,
            "r": best_r,
            "target": best_t
        })

    # Sort sources by the absolute correlation of their BEST feature
    sorted_sources = sorted(
        source_stats.items(), 
        key=lambda item: max(abs(x['r']) for x in item[1]), 
        reverse=True
    )

    print(f"\nTop 10 Sources by max correlation:")
    for i, (src, feats) in enumerate(sorted_sources[:10]):
        # Sort features within this source
        sorted_feats = sorted(feats, key=lambda x: abs(x['r']), reverse=True)
        best_feat = sorted_feats[0]
        
        print(f"{i+1}. {src:<20} | Max r: {best_feat['r']:.3f} (vs {best_feat['target']})")
        
        # Print top 3 indented features
        for f in sorted_feats[:3]:
            print(f"    - {f['feature']:<30} r: {f['r']:.3f} ({f['target']})")
            
    return feature_max_corrs

# ================= STEP 4: SIMILARITY PRUNING =================

def prune_similar_sources(X: pd.DataFrame, target_df: pd.DataFrame, groups: np.ndarray, valid_targets: List[str], ts_source_set: Set[str]) -> pd.DataFrame:
    """
    1. Groups features by Source.
    2. Calculates Source-Source similarity (Average Spearman of all constituent features).
    3. Identifies pairs with similarity > THRESHOLD.
    4. Keeps the source with higher average correlation to targets.
    """
    print(f"\n--- Step 4: Source Redundancy Pruning (Threshold: {SIMILARITY_THRESHOLD}) ---")
    
    # 1. Map features to sources
    source_to_features = defaultdict(list)
    for col in X.columns:
        src = get_source_name(col, ts_source_set)
        source_to_features[src].append(col)
    
    unique_sources = list(source_to_features.keys())
    print(f"Analyzing redundancy among {len(unique_sources)} sources...")

    # 2. Calculate Feature Correlation Matrix
    print("Calculating feature correlation matrix...")
    feat_corr = X.corr(method='spearman').abs()

    # 3. Calculate Source Relevance (Average correlation to targets)
    y_aligned = target_df.set_index("user").reindex(groups)
    source_relevance = {}
    
    for src, feats in source_to_features.items():
        corrs = []
        for f in feats:
            feat_data = X[f]
            if feat_data.std() < 1e-9:
                corrs.append(0)
                continue
                
            for t in valid_targets:
                target_data = y_aligned[t]
                if target_data.std() < 1e-9:
                    corrs.append(0)
                    continue
                    
                # Calculate correlation of each feature to each target
                r, _ = spearmanr(feat_data, target_data)
                corrs.append(abs(r))
        # Relevance is the mean absolute correlation of this source's features to the targets
        source_relevance[src] = np.mean(corrs) if corrs else 0

    # 4. Find High Similarity Source Pairs
    all_pairs = []
    
    # Iterate upper triangle of sources
    for i in range(len(unique_sources)):
        for j in range(i + 1, len(unique_sources)):
            s1 = unique_sources[i]
            s2 = unique_sources[j]
            
            f1 = source_to_features[s1]
            f2 = source_to_features[s2]
            
            # Extract submatrix of correlations between features of s1 and s2
            sub_corr = feat_corr.loc[f1, f2]
            # Average similarity is the mean of all pairwise feature correlations
            avg_sim = sub_corr.values.mean()
            
            all_pairs.append((avg_sim, s1, s2))

    # Sort by similarity (highest first)
    all_pairs.sort(key=lambda x: x[0], reverse=True)
    
    # Report Top 5 Similarities regardless of threshold
    print(f"\nTop 5 Most Similar Source Pairs:")
    for sim, s1, s2 in all_pairs[:5]:
        print(f"   - {s1} vs {s2}: {sim:.4f}")

    # Filter for pruning
    high_sim_pairs = [p for p in all_pairs if p[0] > SIMILARITY_THRESHOLD]
    
    print(f"\nFound {len(high_sim_pairs)} source pairs above threshold ({SIMILARITY_THRESHOLD}).")
    
    dropped_sources = set()
    
    if high_sim_pairs:
        print(f"\n{'Source A':<25} | {'Source B':<25} | {'Sim':<6} | {'Action'}")
        print("-" * 90)
        
        for sim, s1, s2 in high_sim_pairs:
            if s1 in dropped_sources or s2 in dropped_sources:
                continue
                
            rel1 = source_relevance[s1]
            rel2 = source_relevance[s2]
            
            if rel1 >= rel2:
                dropped_sources.add(s2)
                action = f"Drop {s2} (Rel: {rel2:.3f} < {rel1:.3f})"
            else:
                dropped_sources.add(s1)
                action = f"Drop {s1} (Rel: {rel1:.3f} < {rel2:.3f})"
                
            print(f"{s1:<25} | {s2:<25} | {sim:.4f} | {action}")
    else:
        print("No sources pruned.")

    # 5. Drop Features
    features_to_drop = []
    for src in dropped_sources:
        features_to_drop.extend(source_to_features[src])
        
    print(f"\nPruned {len(dropped_sources)} sources ({len(features_to_drop)} features).")
    
    return X.drop(columns=features_to_drop)

# ================= STEP 5: STABILITY FEATURE SELECTION =================

def stability_feature_selection_multitarget(X: pd.DataFrame, target_df: pd.DataFrame, groups: np.ndarray, valid_targets: List[str], ts_source_set: Set[str], feature_corrs: Dict[str, float]) -> Tuple[List[str], List[str]]:
    """
    Runs stability selection at the SOURCE (Channel) level.
    Prevents one channel's variations from crowding out other sensors.
    Returns:
        - List of selected sources
        - List of selected features (based on correlation)
    """
    print(f"\n--- Step 5: Source-Level Stability Selection on {len(valid_targets)} targets ---")
    
    logo = LeaveOneGroupOut()
    
    # Trackers for SOURCES, not specific features
    source_stable_counts = defaultdict(lambda: defaultdict(int)) 
    source_raw_importances = defaultdict(list)
    
    n_folds = logo.get_n_splits(X, target_df[valid_targets[0]], groups)
    stability_threshold = n_folds * SELECTION_THRESHOLD # 50% Threshold

    for t in valid_targets:
        y = target_df.set_index("user").reindex(groups)[t]
        
        for train_idx, _ in logo.split(X, y, groups):
            X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
            
            # Fit RF
            model = RandomForestRegressor(
                n_estimators=N_ESTIMATORS,   # 500
                max_depth=MAX_DEPTH,         # 4
                min_samples_leaf=MIN_SAMPLES_LEAF, # 3
                max_features=MAX_FEATURES,   # "sqrt"
                n_jobs=-1, 
                random_state=RANDOM_STATE
            )
            model.fit(X_train, y_train)
            
            # --- GROUP AGGREGATION STEP ---
            # 1. Calculate Importance per Feature
            raw_imps = pd.Series(model.feature_importances_, index=X.columns)
            
            # 2. Aggregate Importance by Source (Sum)
            source_imps = defaultdict(float)
            for feat, score in raw_imps.items():
                src = get_source_name(feat, ts_source_set)
                source_imps[src] += score
                
            # 3. Store Raw Source Importance (for global stats)
            for src, score in source_imps.items():
                source_raw_importances[src].append(score)
            
            # 4. Rank Sources and Pick Top K (e.g. Top 20 Channels)
            top_k_sources = pd.Series(source_imps).nlargest(TOP_K_SOURCES_PER_FOLD).index.tolist()
            
            # 5. Update Stability Counts
            for src in top_k_sources:
                source_stable_counts[src][t] += 1
                
        # Report specific stats for this target
        n_stable = sum(1 for src in source_stable_counts if source_stable_counts[src][t] >= stability_threshold)
        print(f">> Analyzing Target: {t} -> {n_stable} Sources (Channels) met stability threshold (>= {SELECTION_THRESHOLD*100:.0f}% in folds)")

    # --- POST-PROCESSING & DISPLAY ---
    print("\n--- Aggregating Results by Source ---")
    
    final_stats = []
    unique_sources = list(source_raw_importances.keys())
    
    for src in unique_sources:
        # Check Max Stability across targets
        max_stability_count = 0
        best_target = "None"
        
        for t in valid_targets:
            count = source_stable_counts[src][t]
            if count > max_stability_count:
                max_stability_count = count
                best_target = t
        
        # Calculate Global Mean Importance of the SOURCE
        mean_imp = np.mean(source_raw_importances[src])
        
        # Keep if stable
        if max_stability_count >= stability_threshold:
            final_stats.append({
                "Source": src,
                "Global_Mean_Imp": mean_imp,
                "Max_Stability_Pct": (max_stability_count / n_folds) * 100,
                "Best_Target": best_target
            })

    df_stats = pd.DataFrame(final_stats)
    
    if df_stats.empty:
        print("WARNING: No sources met the stability threshold.")
        return [], []

    # Sort and Display
    df_stats = df_stats.sort_values("Global_Mean_Imp", ascending=False).reset_index(drop=True)
    
    print("\n=== TOP SELECTED SOURCES (Channels/Static) ===")
    print(df_stats.head(20).to_string(formatters={
        'Global_Mean_Imp': '{:,.4f}'.format,
        'Max_Stability_Pct': '{:.1f}%'.format
    }))
    
    # --- RETURN SOURCES DIRECTLY ---
    kept_sources = df_stats["Source"].tolist()
    
    # --- REFINE FEATURES (Correlation-based) ---
    print(f"\n--- Refining Selection: Top Features per Source (Max {MAX_FEATURES_PER_SOURCE}/src, Total {MAX_TOTAL_FEATURES}) ---")
    
    all_candidates = []
    
    for src in kept_sources:
        # Identify features belonging to this source
        src_feats = [f for f in X.columns if get_source_name(f, ts_source_set) == src]
        
        # Sort by correlation (descending)
        src_feats.sort(key=lambda f: feature_corrs.get(f, 0), reverse=True)
        
        # Keep top N per source
        top_n = src_feats[:MAX_FEATURES_PER_SOURCE]
        
        for f in top_n:
            all_candidates.append({
                "feature": f,
                "source": src,
                "corr": feature_corrs.get(f, 0)
            })

    # Sort all candidates by correlation globally
    all_candidates.sort(key=lambda x: x["corr"], reverse=True)
    
    # Apply global cap
    final_features = [x["feature"] for x in all_candidates[:MAX_TOTAL_FEATURES]]

    print(f"Selected {len(kept_sources)} unique sources.")
    print(f"Refined to {len(final_features)} specific features based on correlation.")
    
    return kept_sources, final_features

# ================= STEP 6: EXPORT =================

def export_pruned_data(ts_df: pd.DataFrame, path_df: pd.DataFrame, user_df: pd.DataFrame, target_df: pd.DataFrame, selected_sources: List[str], valid_targets: List[str], kept_features: List[str], ts_source_set: Set[str]):
    print("\n--- Exporting Pruned Dataset ---")
    
    keep_ts_cols = set()
    keep_path_cols = set()
    keep_user_cols = set()
    
    # Identify columns available in source dataframes (excluding keys)
    ts_avail = set(ts_df.columns) - {"user", "path", "time"}
    
    # 1. Filter Time Series Channels (Raw Data)
    for src in selected_sources:
        if src in ts_avail:
            keep_ts_cols.add(src)
    
    # 2. Filter Path Features (Static/Aggregated)
    # Keep if:
    #  a) It is in kept_features (survived pruning) AND its source is selected
    #  b) It IS a selected source (e.g. a raw path feature like 'path_length')
    path_cols = [c for c in path_df.columns if c not in ["user", "path"]]
    for col in path_cols:
        is_relevant = False
        # Direct match (source itself)
        if col in selected_sources:
            is_relevant = True
        # Derived feature match
        elif col in kept_features:
            src = get_source_name(col, ts_source_set)
            if src in selected_sources:
                is_relevant = True
        
        if is_relevant:
            keep_path_cols.add(col)

    # 3. Filter User Features
    user_cols = [c for c in user_df.columns if c != "user"]
    for col in user_cols:
        if col in selected_sources:
            keep_user_cols.add(col)
        elif col in kept_features:
            src = get_source_name(col, ts_source_set)
            if src in selected_sources:
                keep_user_cols.add(col)

    # 2. Slice DataFrames
    ts_pruned = ts_df[["user", "path", "time"] + list(keep_ts_cols)]
    path_pruned = path_df[["user", "path"] + list(keep_path_cols)]
    user_pruned = user_df[["user"] + list(keep_user_cols)]
    target_pruned = target_df[["user"] + valid_targets]

    # 3. Save
    ts_pruned.to_csv(os.path.join(OUT_DIR, "timeseries.csv"), index=False)
    path_pruned.to_csv(os.path.join(OUT_DIR, "path.csv"), index=False)
    user_pruned.to_csv(os.path.join(OUT_DIR, "user.csv"), index=False)
    target_pruned.to_csv(os.path.join(OUT_DIR, "target.csv"), index=False)
    
    print(f"Datasets saved to {OUT_DIR}")
    print(f"Targets: {len(valid_targets)}, TS Channels: {len(keep_ts_cols)}, Path Feats: {len(keep_path_cols)}, User Feats: {len(keep_user_cols)}")

# ================= MAIN =================

def main():
    # Load
    dataset = DatasetConv1s(path=IN_DIR, recreate=False)
    target = dataset.target_df

    # Identify TS source columns from Preprocessor definitions
    ts_source_cols = set(Preprocessor.TIMESERIES_IMPUTE_WITH_ZERO_COLS + Preprocessor.TIMESERIES_IMPUTE_WITH_CLOSEST_COLS)

    # Merge
    X_full, groups = merge_datasets(dataset.path_related_df, dataset.user_related_df)
    
    # Filter Targets
    valid_targets = filter_learnable_targets(X_full, target, groups, min_keep=5, max_keep=MAX_TOP_N_TARGETS)
    
    if not valid_targets:
        print("CRITICAL: No targets are learnable above baseline. Check data quality.")
        return
    
    # 3. Analyze Correlations (Reporting & Feature Scoring)
    feature_corrs = analyze_correlations(X_full, target, groups, valid_targets, ts_source_cols)
    
    # 4. Prune Redundant Sources
    X_pruned = prune_similar_sources(X_full, target, groups, valid_targets, ts_source_cols)
    
    # 5. Run MULTI-TARGET Selection (on Pruned Data)
    stable_sources, stable_features = stability_feature_selection_multitarget(X_pruned, target, groups, valid_targets, ts_source_cols, feature_corrs)
    
    # Export
    export_pruned_data(dataset.timeseries_df, dataset.path_related_df, dataset.user_related_df, target, stable_sources, valid_targets, stable_features, ts_source_cols)

if __name__ == "__main__":
    main()