experiment_info:
  start_time: '2026-02-04 10:21:50'
  duration: 0:44:45
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 38
    - 158
    shape_X_path:
    - 112
    - 20
    - 103
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 13801
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Figure 8 Walk
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  aggregation: attention
  hidden_dim: 128
  dropout: 0.32803618577857374
  lr: 0.00028373023710366845
  weight_decay: 1.5606720113072412e-05
