experiment_info:
  start_time: '2026-01-31 13:58:29'
  duration: 0:53:40
  input_shapes:
    shape_X_ts:
    - 168
    - 20
    - 39
    - 158
    shape_X_path:
    - 168
    - 20
    - 107
    shape_X_user:
    - 168
    - 2
    shape_y:
    - 168
    - 4
  total_model_parameters: 7300
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Balance Test
  - Single Leg Stance
  - Hand Grip Right
  - Throwing Beanbag at Target
  augmentation_ratio: 5
  note: Full hyperparmeter search with augmentation ratio comparison
hyperparameters_fold_0:
  aggregation: mean
  hidden_dim: 64
  depth: 1
  dropout: 0.3779290909679418
  lr: 0.00013536551658488056
  weight_decay: 0.0003494371026829297
