experiment_info:
  start_time: '2026-02-04 07:50:14'
  duration: '1:06:31'
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 38
    - 158
    shape_X_path:
    - 112
    - 20
    - 103
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 22421
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Figure 8 Walk
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  lr: 0.0003312728840071141
  weight_decay: 4.2570184491580955e-05
  lstm_hidden_dim: 32
  lstm_layers: 2
  bidirectional: false
  dropout_lstm: 0.10198230964005602
  path_dim: 16
  dropout_path: 0.37919749595488816
  regressor_dim: 128
  dropout_reg: 0.28866051830181666
  path_aggregation: static
  batch_size: 16
