experiment_info:
  start_time: '2026-01-31 04:41:33'
  duration: '1:14:07'
  input_shapes:
    shape_X_ts:
    - 140
    - 20
    - 39
    - 158
    shape_X_path:
    - 140
    - 20
    - 107
    shape_X_user:
    - 140
    - 2
    shape_y:
    - 140
    - 4
  total_model_parameters: 22776
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Balance Test
  - Single Leg Stance
  - Hand Grip Right
  - Throwing Beanbag at Target
  augmentation_ratio: 4
  note: Full hyperparmeter search with augmentation ratio comparison
hyperparameters_fold_0:
  lr: 0.00011491843130373855
  weight_decay: 0.00016765642235585317
  lstm_hidden_dim: 32
  lstm_layers: 2
  bidirectional: false
  dropout_lstm: 0.1596502496769959
  path_dim: 8
  dropout_path: 0.39854164116688273
  regressor_dim: 256
  dropout_reg: 0.2759837187859439
  path_aggregation: static
  batch_size: 16
