experiment_info:
  start_time: '2026-02-04 00:30:39'
  duration: 0:44:25
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 39
    - 158
    shape_X_path:
    - 112
    - 20
    - 107
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 7213
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Jump & Reach
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  aggregation: attention
  hidden_dim: 64
  dropout: 0.23726735208352348
  lr: 0.0010475175994900396
  weight_decay: 0.0029961855368564687
