experiment_info:
  start_time: '2026-02-03 18:58:07'
  duration: 0:40:08
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 39
    - 158
    shape_X_path:
    - 112
    - 20
    - 107
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 110
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Hand Grip Right
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  aggregation: mean
  lr: 0.0015352850278464367
  weight_decay: 1.2623784346950534e-05
