experiment_info:
  start_time: '2026-01-31 11:27:13'
  duration: 0:48:58
  input_shapes:
    shape_X_ts:
    - 168
    - 20
    - 39
    - 158
    shape_X_path:
    - 168
    - 20
    - 107
    shape_X_user:
    - 168
    - 2
    shape_y:
    - 168
    - 4
  total_model_parameters: 440
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Balance Test
  - Single Leg Stance
  - Hand Grip Right
  - Throwing Beanbag at Target
  augmentation_ratio: 5
  note: Full hyperparmeter search with augmentation ratio comparison
hyperparameters_fold_0:
  aggregation: mean
  lr: 0.0001839948921343881
  alpha: 0.0007328231490816986
  l1_ratio: 0.505460949794341
