experiment_info:
  start_time: '2026-02-04 08:56:46'
  duration: 0:42:34
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 38
    - 158
    shape_X_path:
    - 112
    - 20
    - 103
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 210
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Figure 8 Walk
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  aggregation: attention
  lr: 0.00044066053669840273
  alpha: 0.00010995112336338773
  l1_ratio: 0.2362564623215344
