experiment_info:
  start_time: '2026-02-05 02:48:19'
  duration: 0:47:52
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 39
    - 158
    shape_X_path:
    - 112
    - 20
    - 105
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 6977
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Tapping Test
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  aggregation: mean
  hidden_dim: 64
  depth: 1
  dropout: 0.28356150044122597
  lr: 0.0020711684526786363
  weight_decay: 1.3398446292586853e-05
