experiment_info:
  start_time: '2026-01-30 19:40:05'
  duration: 0:20:52
  input_shapes:
    shape_X_ts:
    - 56
    - 20
    - 39
    - 158
    shape_X_path:
    - 56
    - 20
    - 107
    shape_X_user:
    - 56
    - 2
    shape_y:
    - 56
    - 4
  total_model_parameters: 14704
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Balance Test
  - Single Leg Stance
  - Hand Grip Right
  - Throwing Beanbag at Target
  augmentation_ratio: 1
  note: Full hyperparmeter search with augmentation ratio comparison
hyperparameters_fold_0:
  aggregation: attention
  hidden_dim: 128
  dropout: 0.0650039508498721
  lr: 0.00024982921030097436
  weight_decay: 6.93875646450579e-05
