experiment_info:
  start_time: '2026-02-03 16:18:39'
  duration: 0:54:07
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 39
    - 158
    shape_X_path:
    - 112
    - 20
    - 107
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 9177
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Hand Grip Right
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  ts_out_channels: 16
  num_conv_layers: 2
  path_dim: 8
  regressor_dim: 256
  path_attention_type: mean
  lr: 0.0002636330051260747
  weight_decay: 0.005242343794276826
  dropout: 0.3919208997806445
  batch_size: 16
