experiment_info:
  start_time: '2026-02-03 14:50:14'
  duration: 0:42:04
  input_shapes:
    shape_X_ts:
    - 112
    - 20
    - 39
    - 158
    shape_X_path:
    - 112
    - 20
    - 104
    shape_X_user:
    - 112
    - 2
    shape_y:
    - 112
    - 1
  total_model_parameters: 13930
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Hand Grip Left
  augmentation_ratio: 3
  note: Multitarget to all single target comparison
hyperparameters_fold_0:
  aggregation: attention
  hidden_dim: 128
  dropout: 0.031832722843050165
  lr: 0.0009721411398289347
  weight_decay: 2.5558155121549484e-05
