experiment_info:
  start_time: '2026-01-31 05:55:41'
  duration: 0:41:41
  input_shapes:
    shape_X_ts:
    - 140
    - 20
    - 39
    - 158
    shape_X_path:
    - 140
    - 20
    - 107
    shape_X_user:
    - 140
    - 2
    shape_y:
    - 140
    - 4
  total_model_parameters: 440
pipeline_config:
  epochs: 50
  hyperparameter_mode: optimize_once
  only_first_fold: false
  n_trials: 50
  use_lasso: false
  max_n_features: 20
  targets:
  - Balance Test
  - Single Leg Stance
  - Hand Grip Right
  - Throwing Beanbag at Target
  augmentation_ratio: 4
  note: Full hyperparmeter search with augmentation ratio comparison
hyperparameters_fold_0:
  aggregation: mean
  lr: 0.00014844547911676528
  alpha: 0.00015400786229127943
  l1_ratio: 0.6975116340362131
